version: '3'
services:
  centos-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-centos-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_centos_api:/usr/lib/python3.6/site-packages/vlab_centos_api
    command: ["python3", "app.py"]

  centos-worker:
    image:
      willnx/vlab-centos-worker
    volumes:
      - ./vlab_centos_api:/usr/lib/python3.6/site-packages/vlab_centos_api
      - /mnt/raid/images/centos:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  centos-broker:
    image:
      rabbitmq:3.7-alpine
